"""Remove deck_cards table and update deck-word relationship

Revision ID: 9cadbd5ccb0e
Revises: f9dfbd8d0075
Create Date: 2025-02-12 12:02:32.292635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cadbd5ccb0e'
down_revision = 'f9dfbd8d0075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck_cards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_cards',
    sa.Column('deck_id', sa.INTEGER(), nullable=False),
    sa.Column('word_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'word_id')
    )
    # ### end Alembic commands ###
